// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Either")]
[assembly: AssemblyDescriptionAttribute("A Either type that represents one of two types.")]
[assembly: GuidAttribute("a043d66c-6d45-4038-84a4-6f6b8cf9384d")]
[assembly: AssemblyProductAttribute("Either")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
